version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=WILD_SENSE
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mcp_api:
    image: mcpwildsense/dev-mcp-api:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TOKEN=${TOKEN}
    depends_on:
      - postgres

  mcp_front:
    image: mcpwildsense/dev-mcp-front:latest
    restart: always
    ports:
      - "3030:3030"
    environment:
      - REACT_APP_APIMCP=${REACT_APP_APIMCP}
      - REACT_APP_HEADER=${REACT_APP_HEADER}
      - REACT_APP_TOKEN=${REACT_APP_TOKEN}
      - REACT_APP_AWS_ACCESS_KEY_ID=${REACT_APP_AWS_ACCESS_KEY_ID}
      - REACT_APP_AWS_SECRET_ACCESS_KEY=${REACT_APP_AWS_SECRET_ACCESS_KEY}
      - REACT_APP_AWS_URL=${REACT_APP_AWS_URL}
      - REACT_APP_VISIONMCP=${REACT_APP_VISIONMCP}
      - PORT=${PORT}
    depends_on:
      - mcp_api

  mcp_vision:
    image: mcpwildsense/dev-mcp-vision:latest
    restart: always
    ports:
      - "3001:3001"

  mcp_dashboard:
    image: mcpwildsense/dev-mcp-dashboard:latest
    restart: always
    ports:
      - "4173:4173"
    environment:
      - VITE_REACT_APP_APIMCP=${VITE_REACT_APP_APIMCP}
      - VITE_REACT_APP_HEADER=${VITE_REACT_APP_HEADER}
      - VITE_REACT_APP_TOKEN=${VITE_REACT_APP_TOKEN}

  blazepose-api:
    image: ignaciobarrera/blazepose-api:latest
    restart: always
    ports:
      - "5000:5000"